#!/usr/bin/env bash

set -e

CONFIG="install.conf.json"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

read -p "Please specify Git Author Name: " AUTHORNAME
read -p "Please specify Git Author Email: " AUTHORMAIL
while read -r line
do
  IFS='=' read -r -a array <<< "$line"
  for index in "${!array[@]}"
  do
    # echo "$index ${array[index]}"

    if [[ "${array[index]}" = "GIT_AUTHOR_NAME" && -z "${array[1]}" ]]; then
      # read -p "Please specify Git Author Name: " USERNAME
      sed -i -e"s/^GIT_AUTHOR_NAME=.*/GIT_AUTHOR_NAME=\"$AUTHORNAME\"/" .bash_profile.local

      git config --global user.name "$AUTHORNAME"
    elif [[ "${array[index]}" = "GIT_AUTHOR_EMAIL" && -z "${array[1]}" ]]; then
      sed -i -e"s/^GIT_AUTHOR_EMAIL=.*/GIT_AUTHOR_EMAIL=\"$AUTHORMAIL\"/" .bash_profile.local

      git config --global user.email "$AUTHORMAIL"
    fi

  done
  # name="$line"
  # echo "Name read from file - $line"
done < .bash_profile.local

source ~/.bashrc
